# Generated by Django 2.1.10 on 2020-04-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_voting', '0002_poll_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentpolltype',
            name='type',
            field=models.CharField(choices=[('analog', 'Analog voting'), ('named_electronic', 'Named electronic voting'), ('secret_electronic', 'Secret electronic voting - no delegate board'), ('secret_electronic_board', 'Secret electronic voting - grey seats on delegate board'), ('token_based_electronic', 'Token-based electronic voting'), ('votecollector', 'VoteCollector default (personalized and active keypads only, with single votes)'), ('votecollector_secret', 'VoteCollector secret (no single votes and delegate board)'), ('votecollector_pseudo_secret', 'VoteCollector grey (no single votes, only grey seats on delegate board)'), ('votecollector_anonymous', 'VoteCollector anonymous (anonymous and personalized keypads, with single votes, no delegate board)')], default='analog', max_length=32),
        ),
        migrations.AlterField(
            model_name='motionpolltype',
            name='type',
            field=models.CharField(choices=[('analog', 'Analog voting'), ('named_electronic', 'Named electronic voting'), ('secret_electronic', 'Secret electronic voting - no delegate board'), ('secret_electronic_board', 'Secret electronic voting - grey seats on delegate board'), ('token_based_electronic', 'Token-based electronic voting'), ('votecollector', 'VoteCollector default (personalized and active keypads only, with single votes)'), ('votecollector_secret', 'VoteCollector secret (no single votes and delegate board)'), ('votecollector_pseudo_secret', 'VoteCollector grey (no single votes, only grey seats on delegate board)'), ('votecollector_anonymous', 'VoteCollector anonymous (anonymous and personalized keypads, with single votes, no delegate board)')], default='analog', max_length=32),
        ),
    ]
