# Generated by Django 2.1.10 on 2020-05-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_voting', '0003_poll_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingcontroller',
            options={'default_permissions': (), 'permissions': (('can_manage', 'Can manage voting'), ('can_see_token_voting', 'Can see the token voting interface'), ('can_vote', 'Can vote'), ('go_mobile', 'Start with Mobile View'))},
        ),
    ]
